os:
  - linux

language: php

php:
  - '7.1'

services:
  - postgresql

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing'
  - composer self-update
  - composer install --no-interaction
    #  - composer global require "squizlabs/php_codesniffer=*" 
  - phpenv rehash
  - php artisan key:generate
  - php artisan migrate
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install
  
script:
  - vendor/bin/phpunit --coverage-text
#  - vendor/bin/phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
