os:
  - linux

language: php

php:
  - '7.1'

services:
  - postgresql

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing'
  - psql -c "CREATE USER aghafoor WITH PASSWORD 'admin';" -U postgres  
  - composer self-update
  - composer install --no-interaction
  - pear clear-cache
  - pear install pear/PHP_CodeSniffer  
    #- composer global require "squizlabs/php_codesniffer=*" 
  - phpenv rehash
  - php artisan key:generate
    #  - php artisan migrate
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install
  - phpcs
  - phpcbf
  
script:
  - vendor/bin/phpunit --coverage-text
  - phpcs app/Http/Controllers
